### ISSUE TITLE
Add Color, CSS Variables & Fallbacks, Background, and Unit

### ISSUE THREAD

**Issue by UKCSD** [UKCSD/sp24-cse110-lab3#1]
### **Add Color:**

**Task Steps:**

- [x] rgb(r, g, b) or rgba(r, g, b, a)

- [x] #FFF or #FFFFFF

- [x] hsl(h, s, l) or hsla(h, s, l, a)

- [x] Color name (i.e ‘orange’)

- [x] Wider-gamut color: color(colorspace c1 c2 c3[ / A]) and color-mix(method, color1[ p1], color2[ p2])   

### **Add CSS Variables & Fallbacks:**

**Task Steps:**

- [x] Show at least one example of using a CSS variable that also has a fallback.

### **Add Background:**

**Task Steps:**

- [x] background-color

### **Add Unit:**

**Task Steps:**

- [x] Use 3 unique relative units total 

- [x] Use 3 unique absolute units total
