### ISSUE TITLE
Box Model, Text, Display, Sizing

### ISSUE THREAD

**Issue by UKCSD** [UKCSD/sp24-cse110-lab3#2]
### **Margin:**

**Task Steps:**

- [x] Long (margin-top, margin-bottom, margin-left, margin-right)

- [x] Short (margin: <top> <right> <bottom> <left>)

- [x] Auto margins: margin: auto

### **Padding:**

**Task Steps:**

- [x] Long (padding-top, padding-bottom, padding-left, padding-right)

- [x] Short (padding: <top> <right> <bottom> <left>)

### **Borders:**

**Task Steps:**

- [x] border-style

- [x] border-color

- [x] border-width

- [x] border-radius

### **Text:**

**Task Steps:**

- [x] color

- [x] text-decoration

- [x] text-align

### **Display:**

**Task Steps:**

- [x] Experiment with these values: none, block, inline-block, inline. Include at least two of them in your page.

- [x] Apply these values to the display property

### **Sizing:**

**Task Steps:**

- [x] height

- [x] width

- [x] max-width

- [x] min-width
