### ISSUE TITLE
Position, Pseudo-class, Layouts, Responsiveness, Fonts

### ISSUE THREAD

**Issue by UKCSD** [UKCSD/sp24-cse110-lab3#3]
### **Position:**

**Task Steps:**

- [x] 2 of the following values: static, relative, fixed, absolute, sticky. Apply these values to the position property

### **Pseudo-class:**

**Task Steps:**

- [x] :hover

- [x] :active

### **Flexbox:**

**Task Steps:**

- [x] apply flex to the display property

- [x] Must have more than two children within the element that is using flexbox. Must use minimum three of the flexbox related attributes

### **Grid:**

**Task Steps:**

- [x] apply grid to the display property

- [x] Must have more than two children within the element that is using the grid. Must use a minimum of three of the grid related attributes

### **Responsiveness:**

**Task Steps:**

- [x] At least one query based on the screen width. Media Query

- [x] Check the DevTools in your browser! Make sure your site works and looks fine on the three main types of form factors (Very small screen (phone), tablet or smaller laptop, and desktop).

- [x] The layout of your page should automatically reflow when the size changes, meaning, we shouldn't have to pinch and zoom in a lot to read text, click buttons, etc.

### **Fonts:**

**Task Steps:**

- [x] Include and use a 3rd party font (https://fonts.google.com/ Links to an external site.). You can load the font in either your HTML or your CSS
