### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by UKCSD** [UKCSD/sp24-cse110-lab3#4]
### **CSS Selectors:**

**Task Steps:**

- [x] Class Selector (.class)

- [x] ID Selector (#id)

- [x] Universal Selector (*)

- [x] Element Selector (element) 

- [x] Attribute Selector (e.g. [attribute=foo])      

- [x] Pseudo-class Selector (e.g. p:hover)

- [x] Selector List (element, element)    
               
- [x] Descendant Combinator (element element)

- [x] Child Combinator (element > element)

- [x] General sibling combinator (element ~ element)

- [x] Adjacent sibling combinator (element + element)

- [x] Combining Two Selectors (element.class)

- [x] :has()

- [x] Nested selectors are another type of selector that have recently been adopted in 2023. Here Links to an external site. is some more information about this selector. Please also include at least one type of this selector in your CSS.
