### ISSUE TITLE
CSS Validation, Canvas Submission

### ISSUE THREAD

**Issue by UKCSD** [UKCSD/sp24-cse110-lab3#5]
### **CSS Validation:**

**Task Steps:**

- [x] Validate your CSS through a validator and take a screenshot.

### **Canvas Submission:**

**Task Steps:**

- [x] README.md file with the link to your hosted GitHub Pages site, found at <username>.github.io/sp24-cse110-lab3 (make sure your site link works)

- [x] Standup notes template in standup.md

- [x] Relevant HTML (from Lab 2) and CSS files (from Lab 3)

- [x] Screenshot of CSS validation.
